COE-990: make methods to return return status code and add return status check in command

diff --git a/commands/microservice b/commands/microservice
--- a/commands/microservice
+++ b/commands/microservice
@@ -56,13 +56,14 @@ get_microservice_info() {
 subscribe() {
   local id=$1
   shift # remove id from $@
-  
+  local return=0
   if [[ "$ignoreAlreadyDone" = true ]]; then
     response=$(c8y microservices enable --id "$id" --silentStatusCodes=409 "$@")
     # exit code 9: Already subscribed
     exit_code=$?
     if [[ $exit_code -eq 9 ]]; then
-      exit 0
+      echo "$return"
+      return
     fi
   else
     response=$(c8y microservices enable --id "$id" "$@")
@@ -70,13 +71,12 @@ subscribe() {
   fi
 
   if [[ $exit_code -eq 0 ]]; then
-    echo "Subscribed successfully." >&2
-    exit 0
-
+    echo "$return"
   fi
 
-  echo "Subscribe process failed." >&2
-  exit 1
+  return=1
+  echo "$return"
+
 }
 
 subscribe_with_tenant_id() {
@@ -84,13 +84,15 @@ subscribe_with_tenant_id() {
   local tenant_id=$2
   shift # remove id from $@
   shift # remove tenat_id from $@
+  local return=0
 
   if [[ "$ignoreAlreadyDone" = true ]]; then
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" --silentStatusCodes=409 "$@")
     # exit code 9: Already subscribed
     exit_code=$?
     if [[ $exit_code -eq 9 ]]; then
-      exit 0
+      echo "$return"
+      return
     fi
   else
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" "$@")
@@ -98,12 +100,11 @@ subscribe_with_tenant_id() {
   fi
 
   if [[ $exit_code -eq 0 ]]; then
-    echo "Subscribed successfully." >&2
-    exit 0
+    echo "$return"
   fi
 
-  echo "Subscribe process failed." >&2
-  exit 1
+  return=1
+  echo "$return"
 }
 
 unsubscribe() {
@@ -116,11 +117,11 @@ unsubscribe() {
   # exit code 3: tenant id is not available
   exit_code=$?
   if [[ $exit_code -eq 0 ]]; then
-    echo "Unsubscribed successfully." >&2
-    exit 0
+    local return=0
+    echo "$return"
   else
-    echo "An error occurred, can not finish unsubscribing process." >&2
-    exit 1
+    local return=1
+    echo "$return"
   fi
 }
 
@@ -135,11 +136,11 @@ unsubscribe_with_tenant_id() {
   # exit code 3: tenant id is not available
   exit_code=$?
   if [[ $exit_code -eq 0 ]]; then
-    echo "Unsubscribed successfully." >&2
-    exit 0
+    local return=0
+    echo "$return"
   else
-    echo "An error occurred, can not finish unsubscribing process." >&2
-    exit 1
+    local return=1
+    echo "$return"
   fi
 }
 
@@ -204,10 +205,18 @@ case "$command" in
 
     if [[ -z "$tenant" ]]; then
       echo "Subscribe $type $name to current tenant $C8Y_TENANT"
-      subscribe "$id" "$@"
+      return=$(subscribe "$id" "$@")
     else
       echo "Subscribe $type $name to tenant $tenant"
-      subscribe_with_tenant_id "$id" "$tenant" "$@"
+      return=$(subscribe_with_tenant_id "$id" "$tenant" "$@")
+    fi
+
+    if [[ $return -eq 0 ]]; then
+      echo "Subscribed successfully." >&2
+      exit 0
+    else
+      echo "Subscribe process failed." >&2
+      exit 1
     fi
     ;;
 
@@ -218,11 +227,20 @@ case "$command" in
 
     if [[ -z "$tenant" ]]; then
       echo "Unsubscribe $type $name from current tenant $C8Y_TENANT"
-      unsubscribe "$id" "$@"
+      return=$(unsubscribe "$id" "$@")
     else
       echo "Unsubscribe $type $name from tenant $tenant"
-      unsubscribe_with_tenant_id "$id" "$tenant" "$@"
+      return=$(unsubscribe_with_tenant_id "$id" "$tenant" "$@")
     fi
+
+    if [[ $return -eq 0 ]]; then
+      echo "Unsubscribed successfully." >&2
+      exit 0
+    else
+      echo "Unsubscribe process failed." >&2
+      exit 1
+    fi
+
     ;;
 
   help|-h|--help)
