COE-995: configure exit code for silentStatusCodes 409 when subscribing, add comment about exit code when unsubscribing microservice

diff --git a/commands/microservice b/commands/microservice
--- a/commands/microservice
+++ b/commands/microservice
@@ -54,13 +54,16 @@ subscribe() {
   if [[ "$ignoreAlreadyDone" = true ]]; then
     response=$(c8y microservices enable --id "$id" --silentStatusCodes=409)
   else
-    response=$(c8y microservices enable --id "$id" )
+    response=$(c8y microservices enable --id "$id")
+    if [[ -z $response ]]; then
+      exit 1
+    fi
   fi
 
-  if [[ -z $response ]]; then
-    exit 1
+
+  if [[ -n $response ]]; then
+    echo "Subscribed successfully." >&2
   fi
-  echo "Subscribed successfully." >&2
 
   exit 0
 }
@@ -72,23 +75,25 @@ subscribe_with_tenant_id() {
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" --silentStatusCodes=409)
   else
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id")
+    if [[ -z $response ]]; then
+      exit 1
+    fi
   fi
 
-  if [[ -z $response ]]; then
-    exit 1
+  if [[ -n $response ]]; then
+    echo "Subscribed successfully." >&2
   fi
 
-  echo "Subscribed successfully." >&2
   exit 0
 }
 
 unsubscribe() {
   local id=$1
-  if [[ "$ignoreAlreadyDone" = true ]]; then
-    response=$(c8y microservices disable --id "$id" --silentStatusCodes=409)
-  else
-    response=$(c8y microservices disable --id "$id")
-  fi
+
+  response=$(c8y microservices disable --id "$id")
+
+  # exit code 4: app isn't subscribed to the tenant or app is not available
+  # exit code 3: tenant id is not available
   exit_code=$?
   if [[ $exit_code -eq 0 ]]; then
     echo "Unsubscribed successfully." >&2
@@ -105,12 +110,10 @@ unsubscribe_with_tenant_id() {
   local id=$1
   local tenant_id=$2
 
-  if [[ "$ignoreAlreadyDone" = true ]]; then
-    response=$(c8y tenants disableApplication --tenant "$tenant_id" --application "$id" --silentStatusCodes=409)
-  else
-    response=$(c8y tenants disableApplication --tenant "$tenant_id" --application "$id")
-  fi
+  response=$(c8y tenants disableApplication --tenant "$tenant_id" --application "$id")
 
+  # exit code 4: app isn't subscribed to the tenant or app is not available
+  # exit code 3: tenant id is not available
   exit_code=$?
   if [[ $exit_code -eq 0 ]]; then
     echo "Unsubscribed successfully." >&2
