COE-990: make arguments to be added dynamically

diff --git a/commands/microservice b/commands/microservice
--- a/commands/microservice
+++ b/commands/microservice
@@ -34,10 +34,29 @@ HELP MESSAGE:
 
 EOF
 }
+
+build_command() {
+  local base_command=$1
+  shift
+
+  # Check if ignoreAlreadyDone is set
+  if [[ "$ignoreAlreadyDone" == true ]]; then
+    # Add the silentStatusCodes=409 option to the command
+    base_command+=" --silentStatusCodes=409"
+  fi
+
+  # Check if other arguments are provided
+  if [ $# -ne 0 ]; then
+    for arg in "$@"; do
+      echo "argument: $arg"
+      base_command+=" $arg"
+    done
+  fi
+
+  echo "$base_command"
+}
+
 get_microservice_info() {
-  local id="$1"
-  shift # remove id from $@
-  
   local output=$(c8y microservices get --id "$id" "$@" 2>&1)
   # Check fault if request receives error message from server
   if [[ $output == *"ERROR"* || -z $output ]]; then
@@ -54,53 +73,27 @@ get_microservice_info() {
 }
 
 subscribe() {
-  local id=$1
-  shift # remove id from $@
   local return=0
+  if [[ -z "$tenant" ]]; then
+    echo "Subscribe $type $name to current tenant $C8Y_TENANT"
+    subscribe_command="c8y microservices enable --id \"$id\""
+  else
+    echo "Subscribe $type $name to tenant $tenant"
+    subscribe_command="c8y tenants enableApplication --tenant \"$tenant\" --application \"$id\""
+  fi
+  subscribe_command=$(build_command "$subscribe_command" "$@")
+  echo "command: $subscribe_command" >&2
+
+  response=$(eval "$subscribe_command")
+
+  exit_code=$?
 
   if [[ "$ignoreAlreadyDone" = true ]]; then
-    response=$(c8y microservices enable --id "$id" --silentStatusCodes=409 "$@")
-    # exit code 9: Already subscribed
-    exit_code=$?
     if [[ $exit_code -eq 9 ]]; then
       echo "Already subscribed." >&2
       echo "$return"
       return
     fi
-  else
-    response=$(c8y microservices enable --id "$id" "$@")
-    exit_code=$?
-  fi
-
-  if [[ $exit_code -eq 0 ]]; then
-    echo "$return"
-    return
-  fi
-
-  return=1
-  echo "$return"
-  return
-}
-
-subscribe_with_tenant_id() {
-  local id=$1
-  local tenant_id=$2
-  shift # remove id from $@
-  shift # remove tenat_id from $@
-  local return=0
-
-  if [[ "$ignoreAlreadyDone" = true ]]; then
-    response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" --silentStatusCodes=409 "$@")
-    # exit code 9: Already subscribed
-    exit_code=$?
-    if [[ $exit_code -eq 9 ]]; then
-      echo "Already subscribed." >&2
-      echo "$return"
-      return
-    fi
-  else
-    response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" "$@")
-    exit_code=$?
   fi
 
   if [[ $exit_code -eq 0 ]]; then
@@ -114,10 +107,17 @@ subscribe_with_tenant_id() {
 }
 
 unsubscribe() {
-  local id=$1
-  shift # Remove id from $@
+  if [[ -z "$tenant" ]]; then
+    echo "Unsubscribe $type $name from current tenant $C8Y_TENANT"
+    unsubscribe_command="c8y microservices enable --id \"$id\""
+  else
+    echo "Unsubscribe $type $name from tenant $tenant"
+    unsubscribe_command="c8y tenants disableApplication --tenant \"$tenant\" --application \"$id\""
+  fi
+  unsubscribe_command=$(build_command "$unsubscribe_command" "$@")
+  echo "command: $unsubscribe_command" >&2
 
-  response=$(c8y microservices disable --id "$id" "$@")
+  response=$(eval "$unsubscribe_command")
 
   # exit code 4: app isn't subscribed to the tenant or app is not available
   # exit code 3: tenant id is not available
@@ -129,29 +129,10 @@ unsubscribe() {
     local return=1
     echo "$return"
   fi
+
   return
 }
-
-unsubscribe_with_tenant_id() {
-  local id=$1
-  local tenant_id=$2
-  shift # Remove id from $@
-  shift # Remove tenant_id from $@
-  response=$(c8y tenants disableApplication --tenant "$tenant_id" --application "$id" "$@")
-
-  # exit code 4: app isn't subscribed to the tenant or app is not available
-  # exit code 3: tenant id is not available
-  exit_code=$?
-  if [[ $exit_code -eq 0 ]]; then
-    local return=0
-    echo "$return"
-  else
-    local return=1
-    echo "$return"
-  fi
-  return
-}
-
+#######################################################################################
 command="$1"
 shift
 
@@ -177,7 +158,7 @@ while [[ $# -gt 0 ]]; do
         exit 1
       fi
       ;;
-    --ignoreAlreadyDone|-ignoreAlreadyDone)
+    --ignoreAlreadyDone|-ignoreAlreadyDone|--silentStatusCodes=409)
       ignoreAlreadyDone=true
       ;;
     -h|--help)
@@ -194,30 +175,32 @@ while [[ $# -gt 0 ]]; do
 done
 set -- "${REST_ARGS[@]}" # Get all remain arguments which is not listed in the cases above
 
+# Check command help first
+case "$command" in
+  help|-h|--help)
+    help
+    exit 0
+    ;;
+esac
+
 # Check id availability
 if [[ -z "$id" ]]; then
-  echo "Option --id is required for the '$command' command." >&2
+  echo "Option --id is required." >&2
+  exit 1
+fi
+
+info=($(get_microservice_info "$id" "$@"))
+name="${info[0]}"
+type="${info[1]}"
+
+if [[ $type == "ERROR" ]]; then
   exit 1
 fi
 
 # Execute the command
 case "$command" in
   subscribe)
-    info=($(get_microservice_info "$id" "$@"))
-    name="${info[0]}"
-    type="${info[1]}"
-
-    if [[ $type == "ERROR" ]]; then
-      exit 1
-    fi
-
-    if [[ -z "$tenant" ]]; then
-      echo "Subscribe $type $name to current tenant $C8Y_TENANT"
-      return=$(subscribe "$id" "$@")
-    else
-      echo "Subscribe $type $name to tenant $tenant"
-      return=$(subscribe_with_tenant_id "$id" "$tenant" "$@")
-    fi
+    return=$(subscribe "$@")
 
     if [[ $return -eq 0 ]]; then
       echo "Subscribed successfully." >&2
@@ -229,17 +212,7 @@ case "$command" in
     ;;
 
   unsubscribe)
-    info=($(get_microservice_info "$id" "$@"))
-    name="${info[0]}"
-    type="${info[1]}"
-
-    if [[ -z "$tenant" ]]; then
-      echo "Unsubscribe $type $name from current tenant $C8Y_TENANT"
-      return=$(unsubscribe "$id" "$@")
-    else
-      echo "Unsubscribe $type $name from tenant $tenant"
-      return=$(unsubscribe_with_tenant_id "$id" "$tenant" "$@")
-    fi
+    return=$(unsubscribe "$@")
 
     if [[ $return -eq 0 ]]; then
       echo "Unsubscribed successfully." >&2
@@ -248,12 +221,6 @@ case "$command" in
       echo "Unsubscribe process failed." >&2
       exit 1
     fi
-
-    ;;
-
-  help|-h|--help)
-    help
-    exit 0
     ;;
 
   *)
