COE-990: modify unsubscribe exit code check

diff --git a/commands/microservice b/commands/microservice
--- a/commands/microservice
+++ b/commands/microservice
@@ -106,6 +106,7 @@ subscribe() {
 }
 
 unsubscribe() {
+  local return=0
   if [[ -z "$tenant" ]]; then
     echo "Unsubscribe $type $name from current tenant $C8Y_TENANT"
     unsubscribe_command="c8y microservices disable --id \"$id\""
@@ -117,11 +118,19 @@ unsubscribe() {
 
   response=$(eval "$unsubscribe_command")
 
-  # exit code 4: app isn't subscribed to the tenant or app is not available
+  # exit code 4: app is already unsubscribed from the tenant
   # exit code 3: tenant id is not available
   exit_code=$?
+
+  if [[ "$ignoreAlreadyDone" = true ]]; then
+    if [[ $exit_code -eq 4 ]]; then
+      echo "$type $name is already unsubscribed." >&2
+      echo "$return"
+      return
+    fi
+  fi
+
   if [[ $exit_code -eq 0 ]]; then
-    local return=0
     echo "$return"
   else
     local return=1
