COE-995: use exit code to check for request status

diff --git a/commands/microservice b/commands/microservice
--- a/commands/microservice
+++ b/commands/microservice
@@ -53,19 +53,22 @@ subscribe() {
   local id=$1
   if [[ "$ignoreAlreadyDone" = true ]]; then
     response=$(c8y microservices enable --id "$id" --silentStatusCodes=409)
+    exit_code=$?
+    if [[ $exit_code -eq 9 ]]; then
+      exit 0
+    fi
   else
     response=$(c8y microservices enable --id "$id")
-    if [[ -z $response ]]; then
-      exit 1
-    fi
+    exit_code=$?
   fi
 
-
-  if [[ -n $response ]]; then
+  if [[ $exit_code -eq 0 ]]; then
     echo "Subscribed successfully." >&2
+    exit 0
   fi
 
-  exit 0
+  echo "Subscribe process failed." >&2
+  exit 1
 }
 
 subscribe_with_tenant_id() {
@@ -73,18 +76,22 @@ subscribe_with_tenant_id() {
   local tenant_id=$2
   if [[ "$ignoreAlreadyDone" = true ]]; then
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id" --silentStatusCodes=409)
+    exit_code=$?
+    if [[ $exit_code -eq 9 ]]; then
+      exit 0
+    fi
   else
     response=$(c8y tenants enableApplication --tenant "$tenant_id" --application "$id")
-    if [[ -z $response ]]; then
-      exit 1
-    fi
+    exit_code=$?
   fi
 
-  if [[ -n $response ]]; then
+  if [[ $exit_code -eq 0 ]]; then
     echo "Subscribed successfully." >&2
+    exit 0
   fi
 
-  exit 0
+  echo "Subscribe process failed." >&2
+  exit 1
 }
 
 unsubscribe() {
