COE-991: fix grammar error

diff --git a/commands/tenants b/commands/tenants
--- a/commands/tenants
+++ b/commands/tenants
@@ -48,7 +48,7 @@ create_subtenant() {
     exit 0
   fi
 
-  echo "New sub-tenant created failed." >&2
+  echo "New sub-tenant creation failed." >&2
   exit 1
 }
 
